### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by NotNeo** [jgoldsmith83/garage75#3]
Site needs a responsive fixed footer. Look into bootStrap's footer class id for this one.

**Comment by jgoldsmith83** [comment]
the footer is responsive and was fixed on events and contact pages - are now relative, just below the content.

**Comment by NotNeo** [comment]
Applied footer code to all pages to create a exact style across all pages. Footer is still off in on directions and contact page.
![screenshot from 2016-07-05 17 54 35](https://cloud.githubusercontent.com/assets/8235684/16601279/9faa6308-42d9-11e6-9a07-17f5268b516b.png)

**Comment by NotNeo** [comment]
Footer across all pages is fixed, thank god. Footers are the devil Bobby!
